# Generated by Django 4.1.2 on 2022-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aleannlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='queue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
