# Generated by Django 4.1.2 on 2022-11-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aleannlab', '0003_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='aleannlab.rank'),
            preserve_default=False,
        ),
    ]
